version: '3.4'

services:
  imgclsserver:
    image: arrybn/img-cls-server:latest
    container_name: img-cls-server
    ports:
      - "9090:9090"
    restart: on-failure
    command: ./img-cls-server -p 9090
